# Generated by Django 3.2.5 on 2021-12-26 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211226_0901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserJob',
        ),
    ]
